### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by dawenl** [dawenl/thesis#1]
- [x] Abstract
- [x] Acknowledgement
- [x] List of abbreviations
- [x] Introduction
- [x] Background
- [x] Music tagging
- [x]  Content-aware music recommendation
- [x]  Exposure matrix factorization
- [x]  Causal inference recommendation
- [x]  Conclusion
- [x]  Reference/Citation check
